### ISSUE TITLE
Server Overwhelmed and Unresponsive During Large Number Requests

### ISSUE THREAD

**Issue by Abhay2342** [Abhay2342/live_cc_generator#1]
![imgonline-com-ua-twotoone-PbJFlsLXZv2Ui](https://github.com/Abhay2342/Live_CC_Generator/assets/73768090/f652bf8e-1bba-40e8-9a1e-996ae26e192b)

Dear contributors,

For those new to open source, this issue is a great opportunity to make a meaningful contribution. Please follow the steps outlined in the [README](https://github.com/Abhay2342/Live_CC_Generator/blob/master/README.md) file to clone and run the application locally.

The task involves modifying the app.py file to incorporate input validation, limiting user input to the range of 1-10,000. Additionally, update the HTML to inform users of this restriction and provide a warning prompt if they attempt to exceed this limit.

This enhancement will not only improve the user experience but also ensure that the application operates smoothly within the specified range. Please adhere to the project's [contribution guidelines](https://github.com/Abhay2342/Live_CC_Generator/blob/master/CONTRIBUTING.md) while working on this task.

Thank you for your contribution!

**Comment by harith-hacky03** [comment]
I fixed it Hope it helps.

**Comment by Abhay2342** [comment]
Thank you for your assistance. Could you please remove the dot before all paths in the "tmp" folder? In Vercel, "tmp" is intended to be a temporary folder, but the presence of the dot (.) is causing it to be treated as a dedicated folder. This leads to an error on the server since Vercel's operating system supports only a read-only file system, making it impossible to write our "cards.txt" files.

**Comment by harith-hacky03** [comment]
Its done can we merge it now.

**Comment by Abhay2342** [comment]
Yes! Now everything is working fine.
