### ISSUE TITLE
Implement Input Validation and User Prompt for Empty Input

### ISSUE THREAD

**Issue by Abhay2342** [Abhay2342/live_cc_generator#3]
![no_input](https://github.com/Abhay2342/Live_CC_Generator/assets/73768090/b42055d6-309b-4e79-bf66-27eaa2abafd2)

This issue is tailored for those new to open source, offering a great starting point. Simply follow the steps outlined in the [README](https://github.com/Abhay2342/Live_CC_Generator/blob/master/README.md) file to clone and run the application locally.

Your task involves adding a condition in the app.py file to check whether the user has provided input. If no input is detected, display a warning message and prompt the user to try again.

By addressing this enhancement, you not only enhance the user experience but also contribute to the project's functionality. Ensure that you adhere to the project's [contribution guidelines](https://github.com/Abhay2342/Live_CC_Generator/blob/master/CONTRIBUTING.md) while working on this task.

We appreciate your valuable contribution to the project!

**Comment by maryjonah** [comment]
Hi @Abhay2342, I would like to work on this issue.

**Comment by Abhay2342** [comment]
Sure, Go Ahead!

**Comment by harith-hacky03** [comment]
Okay I am new to open source. I am just having one doubt , Is the big repositories assign work to us ? How to get assigned ? Or can I go with pull request

**Comment by Abhay2342** [comment]
In open-source projects, tasks or issues are often listed on the issue tracker or designated platforms like GitHub. Larger repositories may have maintainers who assign tasks, while in some cases, contributors can self-assign tasks.

**To get started**:
Explore the Issue Tracker: Look for issues labeled as "good first issue" or something similar. These are usually beginner-friendly tasks that are a good starting point.

**Comment and Express Interest**: 
If you find an issue you'd like to work on, comment on it expressing your interest. Ask if you can be assigned to that issue.

**Self-Assigning**: 
Some projects allow contributors to self-assign issues. If this is the case, there might be a button or a command to do this. Check the project's contributing guidelines for information on their process.

**Pull Requests**: 
In some cases, you may also submit a pull request for a specific issue without explicit assignment. However, it's usually a good practice to communicate with the project maintainers first to ensure your work aligns with their goals and guidelines.

Remember to always check and follow the project's contributing guidelines. If you're unsure, reaching out to the maintainers or the community through the project's communication channels (like a mailing list or chat) is a good idea. Open-source communities often appreciate proactive contributors, so don't hesitate to ask questions and express your willingness to contribute.

**Comment by harith-hacky03** [comment]
Thank you for your guidance

**Comment by Abhay2342** [comment]
You're Welcome!!
I assigned you to this issue now you can work on it.

**Comment by harith-hacky03** [comment]
Hope its done and passed vercel checks

**Comment by Abhay2342** [comment]
Thanks, everyone, for putting in the effort!
